version: 2
updates:
  - package-ecosystem: ""
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: ""
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: ""
    directory: "/"
    schedule:
      interval: "daily"
