version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "pip"
    directory: "/linux/"
    schedule:
      interval: "daily"
  - package-ecosystem: "pip"
    directory: "/windows/"
    schedule:
      interval: "daily"
